[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "turing"
version = "0.1.0"
description = "Python Modules used at EPFL for the Turing course"
# dependencies = ["matplotlib"]